### ISSUE TITLE
How to chat without reloading page?

### ISSUE THREAD

**Issue by Pooja153Sawant** [Sireler/realtime-chat#1]
Hi,
       I used your code, it is so helpfull. But i have one error, when i send message then it needs to reload page then only other user can see it. In console i found two error they are mentioned below.
1) Failed to load resource: net::ERR_CONNECTION_REFUSED
2) /realtimeMaster/public/chat:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error).
     
     Thank You!

**Comment by Sireler** [comment]
Hi,
You need to set your root directory of application to /public in a web server configuration.
